// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import { FaGoogle, FaApple } from 'react-icons/fa';


// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>

//         <div className=' flex w-4/5' >
//           {/* text  */}
//           <div className='hidden md:block w-2/5 bg-gradient-to-tr from-gray-500 to-gray-500 relative'>
//             <img src='https://sellingdelawarehomes.com/delaware-real-estate/wp-content/uploads/2019/07/Arranging-Furniture-photo.jpg' className='w-full h-full object-cover absolute mix-blend-overlay' />

//             <div className='py-36 px-12 p-5 '>
//               <p className=' text-white'>The Future Of</p>
//               <h2 className='text-2xl font-bold  text-white'>Living Is Here</h2>
//               <p className='text-white'>Rent House at affordable Prices,
//                 Best offers with better quality</p>
//             </div>
//           </div>

//           {/* login */}
//           <div className='w3/5 rounded-2xl py-26 px-12'>
//             <div className='m-14 min border-2 border-purple-900 rounded-md'>
//               <div className='flex items-center text-center border-b-2 border-purple-900'>
//                 <div className=' p-1 w-2/4 bg-colony-purple rounded-r-md '> <a href='#' className=' text-white text-sm'> login</a></div>
//                 <div className=' p-1 w-2/4  hover:bg-colony-purple'><a href='#' className=' text-purple-900 text-sm'> sign up</a></div>
//               </div>
//               <div className='py-6 text-center'>
//                 <p className='font-bold text-xs'>Please Login into your Account</p>
//               </div>
//               {/* for email lofin */}
//               <div className='flex flex-col items-center px-3'>

//                 <div className='  w-full p-2'>
//                   <p className='text-xs font-bold'>Email address</p>
//                   <input type="email" name="email" className='bg-white border border-purple-900 px-4 py-1 rounded-md outline-none text-l w-full' />
//                 </div>

//                 <div className=' w-full p-2'>
//                   <p className='text-xs font-bold'>Password</p>
//                   <input type={"password"} name="password" className='bg-white border border-purple-900 px-2 py-1 rounded-md outline-none text-l w-full' />

//                 </div>
//                 <div className='flex w-full  '>
//                   <a href='#' className='text-xs text-purple-900 font-bold  w-full text-right pr-3 '>Forgot Password</a>
//                 </div>
//                 <a className=' text-sm border-2 my-3 bg-colony-purple rounded-md w-2/4 text-center py-1 inline-block text-white hover:bg-colony-purple'>
//                   Login
//                 </a>
//                 <p className='text-xs'> Or Connect with</p>
//               </div>

//               {/* for social login */}
//               <div className='flex justify-center my-2'>
//                 <a href='#' className=' p-4 mx-2'> <FaGoogle /> </a>
//                 <a href='#' className=' p-4 mx-2'> <FaApple /> </a>
//               </div>
//             </div>
//           </div>

//         </div>
//       </main>

//     </div >
//   )
// }
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FaGoogle, FaApple } from 'react-icons/fa';


export default function Home() {
  return (

    // <div className=' grid grid-cols-1 grid-cols-5 grid-rows-5 ' >
    <div className=' grid grid-cols-1 grid-cols-5 grid-rows-5 text-white ' >
      {/* form */}
      <div className='col-span-5 row-span-3 items-center text-black h-fit'>

        <div className='my-10'>
          <h2 className='text-2xl text-center '>Contact us</h2>
          <h3 className='text-2sm  text-center '> Get  in touch with us hjegdyrqygusdweq</h3>

        </div>

        {/* <div className=' '> */}
        <form className='flex flex-col-1 flex-wrap text-center justify-center mx-auto my-8'>

          <div className=' w-screen mx-[24%] my-2 '  >
            <label className=' text-left text-xs font-bold py-1' style={{ display: ' block ' }}>Enter Name</label>
            <input type="text" name="name" className='bg-contact-input border px-1 py-2 rounded-md outline-none text-l w-full gap-2.5' />
          </div>

          <div className=' w-full mx-[24%] my-2 '  >
            <label className=' text-left text-xs font-bold py-1' style={{ display: ' block ' }}>Enter email address</label>
            <input type="email" name="eamil" className='bg-contact-input border px-1 py-2 rounded-md outline-none text-l w-full gap-2.5' />
          </div>

          <div className=' w-full mx-[24%] my-2 '  >
            <label className=' text-left text-xs font-bold py-1' style={{ display: ' block ' }}>Enter Phone number</label>
            <input type="tel" name="phone Numbr" className='bg-contact-input border px-1 py-2 rounded-md outline-none text-l w-full gap-2.5' />
          </div>

          <div className=' w-full mx-[24%] my-2'  >
            <label className=' text-left text-xs font-bold py-1' style={{ display: ' block ' }}>Message</label>
            <input type="text" name="message" style={{ height: ' 150px ' }} className='bg-contact-input border px-1 py-2  rounded-md outline-none text-l w-full gap-2.5' />
          </div>

          <div className='w-full mx-[24%] my-2 grid justify-items-stretch'>
            <button className=' justify-self-end p-[10px] w-[32%] border-2 text-sm  bg-colony-purple rounded-md  text-center text-white '>
              Send Message
            </button>
          </div>


        </form>

        {/* </div> */}

      </div>
      {/* contacts*/}
      <div className='bg-colony-purple col-span-5 row-span-5  '>

        <div className='flex flex-col-1 flex-wrap w-full h-full px-11'>
          {/* rignt side */}
          <div className='w-1/2  h-fit'>

            <h1 className='bg-colony-purple text-white my-5 text-center w-24 h-12 border'> LOGO Here  </h1>

            <p className='mb-2 text-sm'>Sign Up for Our newsletter updates</p>

            <div className='bg-white rounded-md w-10/12 pl-4'>
              <input placeholder='Enter your Email' type="email" name="eamil" className='text-black  outline-none text-l w-4/6 gap-2.5' style={{ height: ' 50px ' }} />
              <button type='Submit' id='subscribe' className='bg-colony-light border border-colony-light px-1 w-fit py-2 rounded-md ' style={{ height: ' 60px ' }}> Subscribe</button>
            </div>

            <div className='m-1 flex'>
              {/* not done with image but with div, I tried image via tailwind but it did now show.!!!!  #####*/}
              <div className='bg-hero-pattern border-2 rounded-[100%] bg-white w-12 h-12 m-4'></div>
              <div className='bg-hero-pattern border-2 rounded-[100%] bg-white w-12 h-12 m-4'></div>
              <div className='bg-hero-pattern border-2 rounded-[100%] bg-white w-12 h-12 m-4'></div>
              <div className='bg-hero-pattern border-2 rounded-[100%] bg-white w-12 h-12 m-4'></div>
            </div>
          </div>

          {/* left side */}
          <div className=' w-1/2 py-[11%]'>
            <div className='text-center'>
              <p>Company Company Company</p>
              <p>Company Company Company</p>
              <p>Company Company Company</p>
              <p>Company Company Company</p>
              <p>Company Company Company</p>
              <p>Company Company Company</p>
              <p>Company Company Company</p>
            </div>

          </div>
        </div>

      </div>

    </div>
  )
}
